// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: lidar-data.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_lidar_2ddata_2eproto__INCLUDED
#define GRPC_lidar_2ddata_2eproto__INCLUDED

#include "lidar-data.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace lidar {
namespace collector {

// Interface exported by the server.
class DataService final {
 public:
  static constexpr char const* service_full_name() {
    return "lidar.collector.DataService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 查询 模板
    virtual ::grpc::Status GetLidarData(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_& request, ::lidar::collector::DataResult_* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lidar::collector::DataResult_>> AsyncGetLidarData(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lidar::collector::DataResult_>>(AsyncGetLidarDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lidar::collector::DataResult_>> PrepareAsyncGetLidarData(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lidar::collector::DataResult_>>(PrepareAsyncGetLidarDataRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 查询 模板
      virtual void GetLidarData(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_* request, ::lidar::collector::DataResult_* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetLidarData(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_* request, ::lidar::collector::DataResult_* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::lidar::collector::DataResult_>* AsyncGetLidarDataRaw(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::lidar::collector::DataResult_>* PrepareAsyncGetLidarDataRaw(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetLidarData(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_& request, ::lidar::collector::DataResult_* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lidar::collector::DataResult_>> AsyncGetLidarData(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lidar::collector::DataResult_>>(AsyncGetLidarDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lidar::collector::DataResult_>> PrepareAsyncGetLidarData(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lidar::collector::DataResult_>>(PrepareAsyncGetLidarDataRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetLidarData(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_* request, ::lidar::collector::DataResult_* response, std::function<void(::grpc::Status)>) override;
      void GetLidarData(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_* request, ::lidar::collector::DataResult_* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::lidar::collector::DataResult_>* AsyncGetLidarDataRaw(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::lidar::collector::DataResult_>* PrepareAsyncGetLidarDataRaw(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetLidarData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 查询 模板
    virtual ::grpc::Status GetLidarData(::grpc::ServerContext* context, const ::lidar::collector::DataRequest_* request, ::lidar::collector::DataResult_* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetLidarData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetLidarData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetLidarData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLidarData(::grpc::ServerContext* /*context*/, const ::lidar::collector::DataRequest_* /*request*/, ::lidar::collector::DataResult_* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetLidarData(::grpc::ServerContext* context, ::lidar::collector::DataRequest_* request, ::grpc::ServerAsyncResponseWriter< ::lidar::collector::DataResult_>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetLidarData<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetLidarData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetLidarData() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::lidar::collector::DataRequest_, ::lidar::collector::DataResult_>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::lidar::collector::DataRequest_* request, ::lidar::collector::DataResult_* response) { return this->GetLidarData(context, request, response); }));}
    void SetMessageAllocatorFor_GetLidarData(
        ::grpc::MessageAllocator< ::lidar::collector::DataRequest_, ::lidar::collector::DataResult_>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::lidar::collector::DataRequest_, ::lidar::collector::DataResult_>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetLidarData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLidarData(::grpc::ServerContext* /*context*/, const ::lidar::collector::DataRequest_* /*request*/, ::lidar::collector::DataResult_* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetLidarData(
      ::grpc::CallbackServerContext* /*context*/, const ::lidar::collector::DataRequest_* /*request*/, ::lidar::collector::DataResult_* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetLidarData<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetLidarData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetLidarData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetLidarData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLidarData(::grpc::ServerContext* /*context*/, const ::lidar::collector::DataRequest_* /*request*/, ::lidar::collector::DataResult_* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetLidarData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetLidarData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetLidarData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLidarData(::grpc::ServerContext* /*context*/, const ::lidar::collector::DataRequest_* /*request*/, ::lidar::collector::DataResult_* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetLidarData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetLidarData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetLidarData() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetLidarData(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetLidarData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetLidarData(::grpc::ServerContext* /*context*/, const ::lidar::collector::DataRequest_* /*request*/, ::lidar::collector::DataResult_* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetLidarData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetLidarData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetLidarData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::lidar::collector::DataRequest_, ::lidar::collector::DataResult_>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::lidar::collector::DataRequest_, ::lidar::collector::DataResult_>* streamer) {
                       return this->StreamedGetLidarData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetLidarData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetLidarData(::grpc::ServerContext* /*context*/, const ::lidar::collector::DataRequest_* /*request*/, ::lidar::collector::DataResult_* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetLidarData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::lidar::collector::DataRequest_,::lidar::collector::DataResult_>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetLidarData<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetLidarData<Service > StreamedService;
};

}  // namespace collector
}  // namespace lidar


#endif  // GRPC_lidar_2ddata_2eproto__INCLUDED
