// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: lidar-data.proto

#include "lidar-data.pb.h"
#include "lidar-data.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace lidar {
namespace collector {

static const char* DataService_method_names[] = {
  "/lidar.collector.DataService/GetLidarData",
};

std::unique_ptr< DataService::Stub> DataService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DataService::Stub> stub(new DataService::Stub(channel, options));
  return stub;
}

DataService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetLidarData_(DataService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DataService::Stub::GetLidarData(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_& request, ::lidar::collector::DataResult_* response) {
  return ::grpc::internal::BlockingUnaryCall< ::lidar::collector::DataRequest_, ::lidar::collector::DataResult_, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetLidarData_, context, request, response);
}

void DataService::Stub::async::GetLidarData(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_* request, ::lidar::collector::DataResult_* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::lidar::collector::DataRequest_, ::lidar::collector::DataResult_, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetLidarData_, context, request, response, std::move(f));
}

void DataService::Stub::async::GetLidarData(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_* request, ::lidar::collector::DataResult_* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetLidarData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::lidar::collector::DataResult_>* DataService::Stub::PrepareAsyncGetLidarDataRaw(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::lidar::collector::DataResult_, ::lidar::collector::DataRequest_, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetLidarData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::lidar::collector::DataResult_>* DataService::Stub::AsyncGetLidarDataRaw(::grpc::ClientContext* context, const ::lidar::collector::DataRequest_& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetLidarDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

DataService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DataService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DataService::Service, ::lidar::collector::DataRequest_, ::lidar::collector::DataResult_, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DataService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::lidar::collector::DataRequest_* req,
             ::lidar::collector::DataResult_* resp) {
               return service->GetLidarData(ctx, req, resp);
             }, this)));
}

DataService::Service::~Service() {
}

::grpc::Status DataService::Service::GetLidarData(::grpc::ServerContext* context, const ::lidar::collector::DataRequest_* request, ::lidar::collector::DataResult_* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace lidar
}  // namespace collector

