// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: camera-service.proto
// Protobuf C++ Version: 5.27.2

#include "camera-service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace service {
namespace grpc {

inline constexpr ImageShape_::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : width_{0},
        height_{0},
        channel_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ImageShape_::ImageShape_(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ImageShape_DefaultTypeInternal {
  PROTOBUF_CONSTEXPR ImageShape_DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ImageShape_DefaultTypeInternal() {}
  union {
    ImageShape_ _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ImageShape_DefaultTypeInternal _ImageShape__default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR CameraMeta__InfoEntry_DoNotUse::CameraMeta__InfoEntry_DoNotUse(::_pbi::ConstantInitialized) {}
struct CameraMeta__InfoEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CameraMeta__InfoEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CameraMeta__InfoEntry_DoNotUseDefaultTypeInternal() {}
  union {
    CameraMeta__InfoEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CameraMeta__InfoEntry_DoNotUseDefaultTypeInternal _CameraMeta__InfoEntry_DoNotUse_default_instance_;

inline constexpr BytesBody::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BytesBody::BytesBody(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct BytesBodyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BytesBodyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BytesBodyDefaultTypeInternal() {}
  union {
    BytesBody _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BytesBodyDefaultTypeInternal _BytesBody_default_instance_;

inline constexpr ImageRequest_::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        sn_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        imageshape_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR ImageRequest_::ImageRequest_(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ImageRequest_DefaultTypeInternal {
  PROTOBUF_CONSTEXPR ImageRequest_DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ImageRequest_DefaultTypeInternal() {}
  union {
    ImageRequest_ _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ImageRequest_DefaultTypeInternal _ImageRequest__default_instance_;

inline constexpr CameraMeta_::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : info_{},
        serialnumber_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        modelname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        manufacturename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        deviceversion_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        userdefinedname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        cameratype_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CameraMeta_::CameraMeta_(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CameraMeta_DefaultTypeInternal {
  PROTOBUF_CONSTEXPR CameraMeta_DefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CameraMeta_DefaultTypeInternal() {}
  union {
    CameraMeta_ _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CameraMeta_DefaultTypeInternal _CameraMeta__default_instance_;

inline constexpr CameraMetas::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : data_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CameraMetas::CameraMetas(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct CameraMetasDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CameraMetasDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CameraMetasDefaultTypeInternal() {}
  union {
    CameraMetas _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CameraMetasDefaultTypeInternal _CameraMetas_default_instance_;
}  // namespace grpc
}  // namespace service
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_camera_2dservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_camera_2dservice_2eproto = nullptr;
const ::uint32_t
    TableStruct_camera_2dservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::service::grpc::CameraMeta__InfoEntry_DoNotUse, _has_bits_),
        PROTOBUF_FIELD_OFFSET(::service::grpc::CameraMeta__InfoEntry_DoNotUse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::service::grpc::CameraMeta__InfoEntry_DoNotUse, key_),
        PROTOBUF_FIELD_OFFSET(::service::grpc::CameraMeta__InfoEntry_DoNotUse, value_),
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::service::grpc::CameraMeta_, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::service::grpc::CameraMeta_, _impl_.serialnumber_),
        PROTOBUF_FIELD_OFFSET(::service::grpc::CameraMeta_, _impl_.modelname_),
        PROTOBUF_FIELD_OFFSET(::service::grpc::CameraMeta_, _impl_.manufacturename_),
        PROTOBUF_FIELD_OFFSET(::service::grpc::CameraMeta_, _impl_.deviceversion_),
        PROTOBUF_FIELD_OFFSET(::service::grpc::CameraMeta_, _impl_.userdefinedname_),
        PROTOBUF_FIELD_OFFSET(::service::grpc::CameraMeta_, _impl_.cameratype_),
        PROTOBUF_FIELD_OFFSET(::service::grpc::CameraMeta_, _impl_.info_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::service::grpc::CameraMetas, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::service::grpc::CameraMetas, _impl_.data_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::service::grpc::BytesBody, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::service::grpc::BytesBody, _impl_.content_),
        PROTOBUF_FIELD_OFFSET(::service::grpc::ImageRequest_, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::service::grpc::ImageRequest_, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::service::grpc::ImageRequest_, _impl_.sn_),
        PROTOBUF_FIELD_OFFSET(::service::grpc::ImageRequest_, _impl_.imageshape_),
        ~0u,
        0,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::service::grpc::ImageShape_, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::service::grpc::ImageShape_, _impl_.width_),
        PROTOBUF_FIELD_OFFSET(::service::grpc::ImageShape_, _impl_.height_),
        PROTOBUF_FIELD_OFFSET(::service::grpc::ImageShape_, _impl_.channel_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::service::grpc::CameraMeta__InfoEntry_DoNotUse)},
        {12, -1, -1, sizeof(::service::grpc::CameraMeta_)},
        {27, -1, -1, sizeof(::service::grpc::CameraMetas)},
        {36, -1, -1, sizeof(::service::grpc::BytesBody)},
        {45, 55, -1, sizeof(::service::grpc::ImageRequest_)},
        {57, -1, -1, sizeof(::service::grpc::ImageShape_)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::service::grpc::_CameraMeta__InfoEntry_DoNotUse_default_instance_._instance,
    &::service::grpc::_CameraMeta__default_instance_._instance,
    &::service::grpc::_CameraMetas_default_instance_._instance,
    &::service::grpc::_BytesBody_default_instance_._instance,
    &::service::grpc::_ImageRequest__default_instance_._instance,
    &::service::grpc::_ImageShape__default_instance_._instance,
};
const char descriptor_table_protodef_camera_2dservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024camera-service.proto\022\014service.grpc\032\033go"
    "ogle/protobuf/empty.proto\"\363\001\n\013CameraMeta"
    "_\022\024\n\014serialNumber\030\001 \001(\t\022\021\n\tmodelName\030\002 \001"
    "(\t\022\027\n\017manufactureName\030\003 \001(\t\022\025\n\rdeviceVer"
    "sion\030\004 \001(\t\022\027\n\017userDefinedName\030\005 \001(\t\022\022\n\nc"
    "ameraType\030\006 \001(\t\0221\n\004info\030\007 \003(\0132#.service."
    "grpc.CameraMeta_.InfoEntry\032+\n\tInfoEntry\022"
    "\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"6\n\013Camer"
    "aMetas\022\'\n\004data\030\001 \003(\0132\031.service.grpc.Came"
    "raMeta_\"\034\n\tBytesBody\022\017\n\007content\030\001 \001(\014\"J\n"
    "\rImageRequest_\022\n\n\002sn\030\001 \001(\t\022-\n\nimageShape"
    "\030\002 \001(\0132\031.service.grpc.ImageShape_\"=\n\013Ima"
    "geShape_\022\r\n\005width\030\001 \001(\005\022\016\n\006height\030\002 \001(\005\022"
    "\017\n\007channel\030\003 \001(\0052\325\001\n\rCameraService\022E\n\016Ge"
    "tCameraMetas\022\026.google.protobuf.Empty\032\031.s"
    "ervice.grpc.CameraMetas\"\000\022B\n\010GetImage\022\033."
    "service.grpc.ImageRequest_\032\027.service.grp"
    "c.BytesBody\"\000\0229\n\005Reset\022\026.google.protobuf"
    ".Empty\032\026.google.protobuf.Empty\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_camera_2dservice_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_camera_2dservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_camera_2dservice_2eproto = {
    false,
    false,
    760,
    descriptor_table_protodef_camera_2dservice_2eproto,
    "camera-service.proto",
    &descriptor_table_camera_2dservice_2eproto_once,
    descriptor_table_camera_2dservice_2eproto_deps,
    1,
    6,
    schemas,
    file_default_instances,
    TableStruct_camera_2dservice_2eproto::offsets,
    file_level_enum_descriptors_camera_2dservice_2eproto,
    file_level_service_descriptors_camera_2dservice_2eproto,
};
namespace service {
namespace grpc {
// ===================================================================

CameraMeta__InfoEntry_DoNotUse::CameraMeta__InfoEntry_DoNotUse() {}
CameraMeta__InfoEntry_DoNotUse::CameraMeta__InfoEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
const ::google::protobuf::MessageLite::ClassData*
CameraMeta__InfoEntry_DoNotUse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // tc_table
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(CameraMeta__InfoEntry_DoNotUse, _cached_size_),
              false,
          },
          &CameraMeta__InfoEntry_DoNotUse::MergeImpl,
          &CameraMeta__InfoEntry_DoNotUse::kDescriptorMethods,
          &descriptor_table_camera_2dservice_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
// ===================================================================

class CameraMeta_::_Internal {
 public:
};

CameraMeta_::CameraMeta_(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:service.grpc.CameraMeta_)
}
inline PROTOBUF_NDEBUG_INLINE CameraMeta_::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::service::grpc::CameraMeta_& from_msg)
      : info_{visibility, arena, from.info_},
        serialnumber_(arena, from.serialnumber_),
        modelname_(arena, from.modelname_),
        manufacturename_(arena, from.manufacturename_),
        deviceversion_(arena, from.deviceversion_),
        userdefinedname_(arena, from.userdefinedname_),
        cameratype_(arena, from.cameratype_),
        _cached_size_{0} {}

CameraMeta_::CameraMeta_(
    ::google::protobuf::Arena* arena,
    const CameraMeta_& from)
    : ::google::protobuf::Message(arena) {
  CameraMeta_* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:service.grpc.CameraMeta_)
}
inline PROTOBUF_NDEBUG_INLINE CameraMeta_::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : info_{visibility, arena},
        serialnumber_(arena),
        modelname_(arena),
        manufacturename_(arena),
        deviceversion_(arena),
        userdefinedname_(arena),
        cameratype_(arena),
        _cached_size_{0} {}

inline void CameraMeta_::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CameraMeta_::~CameraMeta_() {
  // @@protoc_insertion_point(destructor:service.grpc.CameraMeta_)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CameraMeta_::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.serialnumber_.Destroy();
  _impl_.modelname_.Destroy();
  _impl_.manufacturename_.Destroy();
  _impl_.deviceversion_.Destroy();
  _impl_.userdefinedname_.Destroy();
  _impl_.cameratype_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
CameraMeta_::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(CameraMeta_, _impl_._cached_size_),
              false,
          },
          &CameraMeta_::MergeImpl,
          &CameraMeta_::kDescriptorMethods,
          &descriptor_table_camera_2dservice_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 1, 111, 2> CameraMeta_::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_CameraMeta__default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::service::grpc::CameraMeta_>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string serialNumber = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CameraMeta_, _impl_.serialnumber_)}},
    // string modelName = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CameraMeta_, _impl_.modelname_)}},
    // string manufactureName = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(CameraMeta_, _impl_.manufacturename_)}},
    // string deviceVersion = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(CameraMeta_, _impl_.deviceversion_)}},
    // string userDefinedName = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(CameraMeta_, _impl_.userdefinedname_)}},
    // string cameraType = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(CameraMeta_, _impl_.cameratype_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string serialNumber = 1;
    {PROTOBUF_FIELD_OFFSET(CameraMeta_, _impl_.serialnumber_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string modelName = 2;
    {PROTOBUF_FIELD_OFFSET(CameraMeta_, _impl_.modelname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string manufactureName = 3;
    {PROTOBUF_FIELD_OFFSET(CameraMeta_, _impl_.manufacturename_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string deviceVersion = 4;
    {PROTOBUF_FIELD_OFFSET(CameraMeta_, _impl_.deviceversion_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string userDefinedName = 5;
    {PROTOBUF_FIELD_OFFSET(CameraMeta_, _impl_.userdefinedname_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string cameraType = 6;
    {PROTOBUF_FIELD_OFFSET(CameraMeta_, _impl_.cameratype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // map<string, string> info = 7;
    {PROTOBUF_FIELD_OFFSET(CameraMeta_, _impl_.info_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(CameraMeta_()._impl_.info_)>(
        1, 0, 0, 9,
        9)},
  }}, {{
    "\30\14\11\17\15\17\12\4"
    "service.grpc.CameraMeta_"
    "serialNumber"
    "modelName"
    "manufactureName"
    "deviceVersion"
    "userDefinedName"
    "cameraType"
    "info"
  }},
};

PROTOBUF_NOINLINE void CameraMeta_::Clear() {
// @@protoc_insertion_point(message_clear_start:service.grpc.CameraMeta_)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.info_.Clear();
  _impl_.serialnumber_.ClearToEmpty();
  _impl_.modelname_.ClearToEmpty();
  _impl_.manufacturename_.ClearToEmpty();
  _impl_.deviceversion_.ClearToEmpty();
  _impl_.userdefinedname_.ClearToEmpty();
  _impl_.cameratype_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* CameraMeta_::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:service.grpc.CameraMeta_)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string serialNumber = 1;
  if (!this->_internal_serialnumber().empty()) {
    const std::string& _s = this->_internal_serialnumber();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "service.grpc.CameraMeta_.serialNumber");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string modelName = 2;
  if (!this->_internal_modelname().empty()) {
    const std::string& _s = this->_internal_modelname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "service.grpc.CameraMeta_.modelName");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string manufactureName = 3;
  if (!this->_internal_manufacturename().empty()) {
    const std::string& _s = this->_internal_manufacturename();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "service.grpc.CameraMeta_.manufactureName");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string deviceVersion = 4;
  if (!this->_internal_deviceversion().empty()) {
    const std::string& _s = this->_internal_deviceversion();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "service.grpc.CameraMeta_.deviceVersion");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // string userDefinedName = 5;
  if (!this->_internal_userdefinedname().empty()) {
    const std::string& _s = this->_internal_userdefinedname();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "service.grpc.CameraMeta_.userDefinedName");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // string cameraType = 6;
  if (!this->_internal_cameratype().empty()) {
    const std::string& _s = this->_internal_cameratype();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "service.grpc.CameraMeta_.cameraType");
    target = stream->WriteStringMaybeAliased(6, _s, target);
  }

  // map<string, string> info = 7;
  if (!_internal_info().empty()) {
    using MapType = ::google::protobuf::Map<std::string, std::string>;
    using WireHelper = _pbi::MapEntryFuncs<std::string, std::string,
                                   _pbi::WireFormatLite::TYPE_STRING,
                                   _pbi::WireFormatLite::TYPE_STRING>;
    const auto& field = _internal_info();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            7, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "service.grpc.CameraMeta_.info");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "service.grpc.CameraMeta_.info");
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            7, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "service.grpc.CameraMeta_.info");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "service.grpc.CameraMeta_.info");
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:service.grpc.CameraMeta_)
  return target;
}

::size_t CameraMeta_::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:service.grpc.CameraMeta_)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // map<string, string> info = 7;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_info_size());
  for (const auto& entry : _internal_info()) {
    total_size += _pbi::MapEntryFuncs<std::string, std::string,
                                   _pbi::WireFormatLite::TYPE_STRING,
                                   _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
  }
  // string serialNumber = 1;
  if (!this->_internal_serialnumber().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_serialnumber());
  }

  // string modelName = 2;
  if (!this->_internal_modelname().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_modelname());
  }

  // string manufactureName = 3;
  if (!this->_internal_manufacturename().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_manufacturename());
  }

  // string deviceVersion = 4;
  if (!this->_internal_deviceversion().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_deviceversion());
  }

  // string userDefinedName = 5;
  if (!this->_internal_userdefinedname().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_userdefinedname());
  }

  // string cameraType = 6;
  if (!this->_internal_cameratype().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_cameratype());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CameraMeta_::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CameraMeta_*>(&to_msg);
  auto& from = static_cast<const CameraMeta_&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:service.grpc.CameraMeta_)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.info_.MergeFrom(from._impl_.info_);
  if (!from._internal_serialnumber().empty()) {
    _this->_internal_set_serialnumber(from._internal_serialnumber());
  }
  if (!from._internal_modelname().empty()) {
    _this->_internal_set_modelname(from._internal_modelname());
  }
  if (!from._internal_manufacturename().empty()) {
    _this->_internal_set_manufacturename(from._internal_manufacturename());
  }
  if (!from._internal_deviceversion().empty()) {
    _this->_internal_set_deviceversion(from._internal_deviceversion());
  }
  if (!from._internal_userdefinedname().empty()) {
    _this->_internal_set_userdefinedname(from._internal_userdefinedname());
  }
  if (!from._internal_cameratype().empty()) {
    _this->_internal_set_cameratype(from._internal_cameratype());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CameraMeta_::CopyFrom(const CameraMeta_& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:service.grpc.CameraMeta_)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CameraMeta_::InternalSwap(CameraMeta_* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.info_.InternalSwap(&other->_impl_.info_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.serialnumber_, &other->_impl_.serialnumber_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.modelname_, &other->_impl_.modelname_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.manufacturename_, &other->_impl_.manufacturename_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.deviceversion_, &other->_impl_.deviceversion_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.userdefinedname_, &other->_impl_.userdefinedname_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cameratype_, &other->_impl_.cameratype_, arena);
}

::google::protobuf::Metadata CameraMeta_::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CameraMetas::_Internal {
 public:
};

CameraMetas::CameraMetas(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:service.grpc.CameraMetas)
}
inline PROTOBUF_NDEBUG_INLINE CameraMetas::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::service::grpc::CameraMetas& from_msg)
      : data_{visibility, arena, from.data_},
        _cached_size_{0} {}

CameraMetas::CameraMetas(
    ::google::protobuf::Arena* arena,
    const CameraMetas& from)
    : ::google::protobuf::Message(arena) {
  CameraMetas* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:service.grpc.CameraMetas)
}
inline PROTOBUF_NDEBUG_INLINE CameraMetas::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : data_{visibility, arena},
        _cached_size_{0} {}

inline void CameraMetas::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CameraMetas::~CameraMetas() {
  // @@protoc_insertion_point(destructor:service.grpc.CameraMetas)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void CameraMetas::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
CameraMetas::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(CameraMetas, _impl_._cached_size_),
              false,
          },
          &CameraMetas::MergeImpl,
          &CameraMetas::kDescriptorMethods,
          &descriptor_table_camera_2dservice_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> CameraMetas::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_CameraMetas_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::service::grpc::CameraMetas>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .service.grpc.CameraMeta_ data = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CameraMetas, _impl_.data_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .service.grpc.CameraMeta_ data = 1;
    {PROTOBUF_FIELD_OFFSET(CameraMetas, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::service::grpc::CameraMeta_>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void CameraMetas::Clear() {
// @@protoc_insertion_point(message_clear_start:service.grpc.CameraMetas)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* CameraMetas::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:service.grpc.CameraMetas)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .service.grpc.CameraMeta_ data = 1;
  for (unsigned i = 0, n = static_cast<unsigned>(
                           this->_internal_data_size());
       i < n; i++) {
    const auto& repfield = this->_internal_data().Get(i);
    target =
        ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
            1, repfield, repfield.GetCachedSize(),
            target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:service.grpc.CameraMetas)
  return target;
}

::size_t CameraMetas::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:service.grpc.CameraMetas)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated .service.grpc.CameraMeta_ data = 1;
  total_size += 1UL * this->_internal_data_size();
  for (const auto& msg : this->_internal_data()) {
    total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void CameraMetas::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CameraMetas*>(&to_msg);
  auto& from = static_cast<const CameraMetas&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:service.grpc.CameraMetas)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_data()->MergeFrom(
      from._internal_data());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CameraMetas::CopyFrom(const CameraMetas& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:service.grpc.CameraMetas)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CameraMetas::InternalSwap(CameraMetas* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
}

::google::protobuf::Metadata CameraMetas::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class BytesBody::_Internal {
 public:
};

BytesBody::BytesBody(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:service.grpc.BytesBody)
}
inline PROTOBUF_NDEBUG_INLINE BytesBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::service::grpc::BytesBody& from_msg)
      : content_(arena, from.content_),
        _cached_size_{0} {}

BytesBody::BytesBody(
    ::google::protobuf::Arena* arena,
    const BytesBody& from)
    : ::google::protobuf::Message(arena) {
  BytesBody* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:service.grpc.BytesBody)
}
inline PROTOBUF_NDEBUG_INLINE BytesBody::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : content_(arena),
        _cached_size_{0} {}

inline void BytesBody::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
BytesBody::~BytesBody() {
  // @@protoc_insertion_point(destructor:service.grpc.BytesBody)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void BytesBody::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.content_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
BytesBody::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(BytesBody, _impl_._cached_size_),
              false,
          },
          &BytesBody::MergeImpl,
          &BytesBody::kDescriptorMethods,
          &descriptor_table_camera_2dservice_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> BytesBody::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_BytesBody_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::service::grpc::BytesBody>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes content = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(BytesBody, _impl_.content_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes content = 1;
    {PROTOBUF_FIELD_OFFSET(BytesBody, _impl_.content_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void BytesBody::Clear() {
// @@protoc_insertion_point(message_clear_start:service.grpc.BytesBody)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.content_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* BytesBody::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:service.grpc.BytesBody)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes content = 1;
  if (!this->_internal_content().empty()) {
    const std::string& _s = this->_internal_content();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:service.grpc.BytesBody)
  return target;
}

::size_t BytesBody::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:service.grpc.BytesBody)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes content = 1;
  if (!this->_internal_content().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_content());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void BytesBody::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BytesBody*>(&to_msg);
  auto& from = static_cast<const BytesBody&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:service.grpc.BytesBody)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BytesBody::CopyFrom(const BytesBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:service.grpc.BytesBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BytesBody::InternalSwap(BytesBody* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.content_, &other->_impl_.content_, arena);
}

::google::protobuf::Metadata BytesBody::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ImageRequest_::_Internal {
 public:
  using HasBits =
      decltype(std::declval<ImageRequest_>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ImageRequest_, _impl_._has_bits_);
};

ImageRequest_::ImageRequest_(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:service.grpc.ImageRequest_)
}
inline PROTOBUF_NDEBUG_INLINE ImageRequest_::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::service::grpc::ImageRequest_& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        sn_(arena, from.sn_) {}

ImageRequest_::ImageRequest_(
    ::google::protobuf::Arena* arena,
    const ImageRequest_& from)
    : ::google::protobuf::Message(arena) {
  ImageRequest_* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.imageshape_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::service::grpc::ImageShape_>(
                              arena, *from._impl_.imageshape_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:service.grpc.ImageRequest_)
}
inline PROTOBUF_NDEBUG_INLINE ImageRequest_::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        sn_(arena) {}

inline void ImageRequest_::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.imageshape_ = {};
}
ImageRequest_::~ImageRequest_() {
  // @@protoc_insertion_point(destructor:service.grpc.ImageRequest_)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ImageRequest_::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.sn_.Destroy();
  delete _impl_.imageshape_;
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ImageRequest_::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(ImageRequest_, _impl_._cached_size_),
              false,
          },
          &ImageRequest_::MergeImpl,
          &ImageRequest_::kDescriptorMethods,
          &descriptor_table_camera_2dservice_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 37, 2> ImageRequest_::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ImageRequest_, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ImageRequest__default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::service::grpc::ImageRequest_>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .service.grpc.ImageShape_ imageShape = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(ImageRequest_, _impl_.imageshape_)}},
    // string sn = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ImageRequest_, _impl_.sn_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string sn = 1;
    {PROTOBUF_FIELD_OFFSET(ImageRequest_, _impl_.sn_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .service.grpc.ImageShape_ imageShape = 2;
    {PROTOBUF_FIELD_OFFSET(ImageRequest_, _impl_.imageshape_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::service::grpc::ImageShape_>()},
  }}, {{
    "\32\2\0\0\0\0\0\0"
    "service.grpc.ImageRequest_"
    "sn"
  }},
};

PROTOBUF_NOINLINE void ImageRequest_::Clear() {
// @@protoc_insertion_point(message_clear_start:service.grpc.ImageRequest_)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sn_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.imageshape_ != nullptr);
    _impl_.imageshape_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ImageRequest_::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:service.grpc.ImageRequest_)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string sn = 1;
  if (!this->_internal_sn().empty()) {
    const std::string& _s = this->_internal_sn();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "service.grpc.ImageRequest_.sn");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .service.grpc.ImageShape_ imageShape = 2;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *_impl_.imageshape_, _impl_.imageshape_->GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:service.grpc.ImageRequest_)
  return target;
}

::size_t ImageRequest_::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:service.grpc.ImageRequest_)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string sn = 1;
  if (!this->_internal_sn().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_sn());
  }

  // .service.grpc.ImageShape_ imageShape = 2;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size +=
        1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.imageshape_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ImageRequest_::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ImageRequest_*>(&to_msg);
  auto& from = static_cast<const ImageRequest_&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:service.grpc.ImageRequest_)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_sn().empty()) {
    _this->_internal_set_sn(from._internal_sn());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.imageshape_ != nullptr);
    if (_this->_impl_.imageshape_ == nullptr) {
      _this->_impl_.imageshape_ =
          ::google::protobuf::Message::CopyConstruct<::service::grpc::ImageShape_>(arena, *from._impl_.imageshape_);
    } else {
      _this->_impl_.imageshape_->MergeFrom(*from._impl_.imageshape_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ImageRequest_::CopyFrom(const ImageRequest_& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:service.grpc.ImageRequest_)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ImageRequest_::InternalSwap(ImageRequest_* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.sn_, &other->_impl_.sn_, arena);
  swap(_impl_.imageshape_, other->_impl_.imageshape_);
}

::google::protobuf::Metadata ImageRequest_::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ImageShape_::_Internal {
 public:
};

ImageShape_::ImageShape_(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:service.grpc.ImageShape_)
}
ImageShape_::ImageShape_(
    ::google::protobuf::Arena* arena, const ImageShape_& from)
    : ImageShape_(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ImageShape_::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ImageShape_::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, width_),
           0,
           offsetof(Impl_, channel_) -
               offsetof(Impl_, width_) +
               sizeof(Impl_::channel_));
}
ImageShape_::~ImageShape_() {
  // @@protoc_insertion_point(destructor:service.grpc.ImageShape_)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ImageShape_::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ImageShape_::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(ImageShape_, _impl_._cached_size_),
              false,
          },
          &ImageShape_::MergeImpl,
          &ImageShape_::kDescriptorMethods,
          &descriptor_table_camera_2dservice_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> ImageShape_::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ImageShape__default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::service::grpc::ImageShape_>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 width = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ImageShape_, _impl_.width_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ImageShape_, _impl_.width_)}},
    // int32 height = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ImageShape_, _impl_.height_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ImageShape_, _impl_.height_)}},
    // int32 channel = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ImageShape_, _impl_.channel_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(ImageShape_, _impl_.channel_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 width = 1;
    {PROTOBUF_FIELD_OFFSET(ImageShape_, _impl_.width_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 height = 2;
    {PROTOBUF_FIELD_OFFSET(ImageShape_, _impl_.height_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 channel = 3;
    {PROTOBUF_FIELD_OFFSET(ImageShape_, _impl_.channel_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ImageShape_::Clear() {
// @@protoc_insertion_point(message_clear_start:service.grpc.ImageShape_)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.width_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.channel_) -
      reinterpret_cast<char*>(&_impl_.width_)) + sizeof(_impl_.channel_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ImageShape_::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:service.grpc.ImageShape_)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 width = 1;
  if (this->_internal_width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_width(), target);
  }

  // int32 height = 2;
  if (this->_internal_height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_height(), target);
  }

  // int32 channel = 3;
  if (this->_internal_channel() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_channel(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:service.grpc.ImageShape_)
  return target;
}

::size_t ImageShape_::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:service.grpc.ImageShape_)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // int32 width = 1;
  if (this->_internal_width() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_width());
  }

  // int32 height = 2;
  if (this->_internal_height() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_height());
  }

  // int32 channel = 3;
  if (this->_internal_channel() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_channel());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ImageShape_::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ImageShape_*>(&to_msg);
  auto& from = static_cast<const ImageShape_&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:service.grpc.ImageShape_)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_width() != 0) {
    _this->_impl_.width_ = from._impl_.width_;
  }
  if (from._internal_height() != 0) {
    _this->_impl_.height_ = from._impl_.height_;
  }
  if (from._internal_channel() != 0) {
    _this->_impl_.channel_ = from._impl_.channel_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ImageShape_::CopyFrom(const ImageShape_& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:service.grpc.ImageShape_)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ImageShape_::InternalSwap(ImageShape_* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ImageShape_, _impl_.channel_)
      + sizeof(ImageShape_::_impl_.channel_)
      - PROTOBUF_FIELD_OFFSET(ImageShape_, _impl_.width_)>(
          reinterpret_cast<char*>(&_impl_.width_),
          reinterpret_cast<char*>(&other->_impl_.width_));
}

::google::protobuf::Metadata ImageShape_::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace grpc
}  // namespace service
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_camera_2dservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
